### ISSUE TITLE
Building the image fails due to base image that does not exists 

### ISSUE THREAD

**Issue by ormergi** [EdDev/django-testing-tutorial#18]
The image `quay.io/centos/centos@sha256:82b0e76b18388f04b38267120b1178f187b5cb0b170c37bcbc6d796114b8e7be`
Does not exists anymore.
Looks like a new digest been pushed, and override the old one, day after the docker file was uploaded https://quay.io/repository/centos/centos?tab=tags&tag=stream8

In general to ensure the image is pinned its more safe to mirror the image to your own registry.
I suggest to use `stream8` tag instead or switch to more stable image.

**Comment by EdDev** [comment]
Thank you for noticing this.
This has been handled by https://github.com/EdDev/django-testing-tutorial/pull/17.
